name: ci-linux
on:
  # release:
  #   types: [created]
  pull_request:
    branches: [main]
    paths-ignore:
      - "doc/**"
      - ".gitignore"
      - ".gitattributes"
      - "README.md"
      - "LICENSE"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    name: Build Linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: create build dir
        run: mkdir build
      - name: cmake generator
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        working-directory: build
      - name: cmake build
        run: |
          cmake --build . --config=${{ matrix.build_type }} -j4
        working-directory: build
      - name: CTest
        run: ctest --output-on-failure -V
        working-directory: build
      # - name: cmake install
      #   run: sudo cmake --build . --target install --config ${{ matrix.build_type }} -j4
      #   working-directory: build
      # - name: cmake package
      #   run: sudo cmake --build . --target package --config ${{ matrix.build_type }} -j4
      #   working-directory: build
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #       generate_release_notes: true
      #       prerelease: false
      #       files: "build/*.zip"
